[tool.poetry]
name = "hexlet-code"
version = "no"
description = "no"
authors = ["Viktory <vberkle@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
